pivotal-container-service_pks_tls_certificate: ((pas_network_cert.certificate))
pivotal-container-service_pks_tls_privatekey: ((pas_network_cert.private_key))
cloud_provider_azure_subscription_id: ((subscription_id))
cloud_provider_azure_tenant_id: ((tenant_id))
