app_graceful_shutdown_period_in_seconds: 10
autoscale_api_disable_connection_pooling: false
autoscale_api_instance_count: 1
autoscale_enable_notifications: true
autoscale_enable_verbose_logging: false
autoscale_instance_count: 3
autoscale_metric_bucket_count: 120
autoscale_scaling_interval_in_seconds: 35
ccdb_connection_validation_timeout: 3600
ccdb_read_timeout: 3600
cf_networking_database_connection_timeout: 120
cf_networking_enable_space_developer_self_service: false
cloud_controller_allow_app_ssh_access: true
cloud_controller_audit_events_cutoff_age_in_days: 31
cloud_controller_completed_tasks_cutoff_age_in_days: 31
cloud_controller_default_app_memory: 1024
cloud_controller_default_app_ssh_access: true
cloud_controller_default_disk_quota_app: 1024
cloud_controller_default_health_check_timeout: 60
cloud_controller_default_quota_max_number_services: 100
cloud_controller_default_quota_memory_limit_mb: 10240
cloud_controller_enable_custom_buildpacks: true
cloud_controller_max_disk_quota_app: 2048
cloud_controller_max_file_size: 1024
cloud_controller_max_package_size: 2147483648
cloud_controller_security_event_logging_enabled: true
cloud_controller_staging_timeout_in_seconds: 900
cloud_controller_temporary_disable_deployments: false
container_networking_interface_plugin_silk_enable_log_traffic: false
container_networking_interface_plugin_silk_enable_policy_enforcement: true
container_networking_interface_plugin_silk_iptables_accepted_udp_logs_per_sec: 100
container_networking_interface_plugin_silk_iptables_denied_logs_per_sec: 1
container_networking_interface_plugin_silk_network_mtu: 1454
container_networking_interface_plugin_silk_vtep_port: 4789
credhub_internal_provider_keys_0_primary: false
diego_brain_starting_container_count_maximum: 200
diego_database_max_open_connections: 100
disable_logs_in_firehose: false
enable_garden_containerd_mode: true
enable_log_cache_syslog_ingestion: false
enable_smb_volume_driver: true
enable_tls_to_internal_pxc: false
enable_v1_firehose: true
enable_v2_firehose: true
garden_disk_cleanup_reserved_reserved_space_for_other_jobs_in_mb: 15360
gorouter_ssl_ciphers: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
ha_proxy_skip_cert_verify: false
haproxy_max_buffer_size: 16384
haproxy_ssl_ciphers: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
locket_database_max_open_connections: 200
log_cache_max_per_source: 100000
metric_registrar_blacklisted_tags: deployment,job,index,id
metric_registrar_enabled: true
metric_registrar_scrape_interval_in_seconds: 35
mysql_activity_logging_enable_audit_logging_events: connect,query
mysql_cli_history: true
mysql_max_connections: 3500
mysql_monitor_poll_frequency: 30
mysql_monitor_write_read_delay: 20
mysql_prevent_node_auto_rejoin: false
mysql_proxy_enable_inactive_mysql_port: false
mysql_proxy_shutdown_delay: 30
mysql_proxy_startup_delay: 0
mysql_remote_admin_access: false
networkpolicyserver_database_max_open_connections: 200
networkpolicyserverinternal_database_max_open_connections: 200
nfs_server_blobstore_internal_access_rules: allow 10.0.0.0/8;,allow 172.16.0.0/12;,allow
  192.168.0.0/16;
push_apps_manager_app_poll_interval: 10
push_apps_manager_buildpack: staticfile_buildpack
push_apps_manager_currency_lookup: '{ "usd": "$", "eur": "€" }'
push_apps_manager_display_plan_prices: false
push_apps_manager_enable_invitations: true
push_apps_manager_invitations_buildpack: nodejs_buildpack
push_apps_manager_poll_interval: 30
push_apps_manager_search_server_buildpack: nodejs_buildpack
push_usage_service_cutoff_age_in_days: 365
route_services_enable_ignore_ssl_cert_verification: false
route_services_enable_internal_lookup: false
router_backend_max_conn: 500
router_disable_insecure_cookies: false
router_drain_timeout: 900
router_drain_wait: 20
router_enable_isolated_routing: false
router_enable_proxy: false
router_enable_write_access_logs: true
router_enable_zipkin: true
router_frontend_idle_timeout: 900
router_lb_healthy_threshold: 20
router_request_timeout_in_seconds: 900
routing_disable_http: false
saml_signature_algorithm: SHA256
secure_service_instance_credentials: false
service_discovery_controller_staleness_threshold: 600
silk_database_max_open_connections: 200
smtp_auth_mechanism: plain
smtp_enable_starttls_auto: false
syslog_drop_debug: true
syslog_use_tcp_for_file_forwarding_local_transport: false
system_blobstore_ccdroplet_max_staged_droplets_stored: 2
system_blobstore_ccpackage_max_valid_packages_stored: 2
system_metrics_scraper_scrape_interval: 1m
uaa_apps_manager_access_token_lifetime: 3600
uaa_cf_cli_access_token_lifetime: 7200
uaa_cf_cli_refresh_token_lifetime: 1209600
uaa_customize_password_label: Password
uaa_customize_username_label: Email
uaa_enable_uri_encoding_compatibility_mode: true
uaa_internal_password_expires_after_months: 0
uaa_internal_password_max_retry: 5
uaa_internal_password_min_length: 0
uaa_internal_password_min_lowercase: 0
uaa_internal_password_min_numeric: 0
uaa_internal_password_min_special: 0
uaa_internal_password_min_uppercase: 0
uaa_proxy_ips_regex: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
uaa_session_cookie_max_age: 28800
uaa_session_idle_timeout: 1800
deploy-autoscaler_post_deploy_state: default
deploy-notifications-ui_post_deploy_state: default
deploy-notifications_post_deploy_state: default
metric_registrar_smoke_test_post_deploy_state: default
nfsbrokerpush_post_deploy_state: default
push-apps-manager_post_deploy_state: default
push-usage-service_post_deploy_state: default
rotate_cc_database_key_post_deploy_state: default
smbbrokerpush_post_deploy_state: default
smoke_tests_post_deploy_state: default
test-autoscaling_post_deploy_state: default
resource-var-backup_restore_instance_type: automatic
resource-var-backup_restore_instances: automatic
resource-var-backup_restore_max_in_flight: default
resource-var-backup_restore_persistent_disk_size: automatic
resource-var-clock_global_instance_type: automatic
resource-var-clock_global_instances: automatic
resource-var-clock_global_max_in_flight: default
resource-var-cloud_controller_instance_type: automatic
resource-var-cloud_controller_instances: automatic
resource-var-cloud_controller_max_in_flight: default
resource-var-cloud_controller_worker_instance_type: automatic
resource-var-cloud_controller_worker_instances: automatic
resource-var-cloud_controller_worker_max_in_flight: default
resource-var-credhub_instance_type: automatic
resource-var-credhub_instances: automatic
resource-var-credhub_max_in_flight: default
resource-var-diego_brain_instance_type: automatic
resource-var-diego_brain_instances: automatic
resource-var-diego_brain_max_in_flight: default
resource-var-diego_cell_instance_type: automatic
resource-var-diego_cell_instances: automatic
resource-var-diego_cell_max_in_flight: default
resource-var-diego_database_instance_type: automatic
resource-var-diego_database_instances: automatic
resource-var-diego_database_max_in_flight: default
resource-var-doppler_instance_type: automatic
resource-var-doppler_instances: automatic
resource-var-doppler_max_in_flight: default
resource-var-ha_proxy_instance_type: automatic
resource-var-ha_proxy_instances: automatic
resource-var-ha_proxy_max_in_flight: default
resource-var-istio_control_instance_type: automatic
resource-var-istio_control_instances: automatic
resource-var-istio_control_max_in_flight: default
resource-var-istio_router_instance_type: automatic
resource-var-istio_router_instances: automatic
resource-var-istio_router_max_in_flight: default
resource-var-loggregator_trafficcontroller_instance_type: automatic
resource-var-loggregator_trafficcontroller_instances: automatic
resource-var-loggregator_trafficcontroller_max_in_flight: default
resource-var-mysql_instance_type: automatic
resource-var-mysql_instances: automatic
resource-var-mysql_max_in_flight: default
resource-var-mysql_monitor_instance_type: automatic
resource-var-mysql_monitor_instances: automatic
resource-var-mysql_monitor_max_in_flight: default
resource-var-mysql_persistent_disk_size: automatic
resource-var-mysql_proxy_instance_type: automatic
resource-var-mysql_proxy_instances: automatic
resource-var-mysql_proxy_max_in_flight: default
resource-var-nats_instance_type: automatic
resource-var-nats_instances: automatic
resource-var-nats_max_in_flight: default
resource-var-nfs_server_instance_type: automatic
resource-var-nfs_server_instances: automatic
resource-var-nfs_server_max_in_flight: default
resource-var-nfs_server_persistent_disk_size: automatic
resource-var-route_syncer_instance_type: automatic
resource-var-route_syncer_instances: automatic
resource-var-route_syncer_max_in_flight: default
resource-var-router_instance_type: automatic
resource-var-router_instances: automatic
resource-var-router_max_in_flight: default
resource-var-tcp_router_instance_type: automatic
resource-var-tcp_router_instances: automatic
resource-var-tcp_router_max_in_flight: default
resource-var-uaa_instance_type: automatic
resource-var-uaa_instances: automatic
resource-var-uaa_max_in_flight: default
