grafana_enable_login_form: true
grafana_enable_mysql: false
grafana_enable_rabbitmq: false
opsman_skip_ssl_validation: false
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
tsdb_canary_exporter_port: 9115
tsdb_disk_chunk_size: 6144
tsdb_memory_chunk_size: 4096
tsdb_scrape_interval: 15s
smoke-test_post_deploy_state: default
update-admin-password_post_deploy_state: default
resource-var-grafana_instance_type: automatic
resource-var-grafana_instances: automatic
resource-var-grafana_max_in_flight: default
resource-var-grafana_persistent_disk_size: automatic
resource-var-pxc-proxy_instance_type: automatic
resource-var-pxc-proxy_instances: automatic
resource-var-pxc-proxy_max_in_flight: default
resource-var-pxc-proxy_persistent_disk_size: automatic
resource-var-pxc_instance_type: automatic
resource-var-pxc_instances: automatic
resource-var-pxc_max_in_flight: default
resource-var-pxc_persistent_disk_size: automatic
resource-var-tsdb_instance_type: automatic
resource-var-tsdb_max_in_flight: default
resource-var-tsdb_persistent_disk_size: automatic
