resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    branch: ((pipeline_params.repo.branch))
    password: ((github-token))
    uri: ((pipeline_params.repo.uri))
    # username: ((github_username))
    paths:
    - "environments/((pipeline_params.iaas))/((pipeline_params.foundation))/config"

- name: pivnet_product
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: ((pipeline_params.pivnet-product.slug_slug))
    product_version: ((pipeline_params.pivnet-product.version))

- name: s3_product
  type: s3
  source:
    bucket: ((pipeline_params.s3_products.bucket))
    region_name: ((pipeline_params.s3_products.region_name))
    access_key_id: ((minio.access_key))
    secret_access_key: ((minio.secret_access_key))
    endpoint: ((pipeline_params.s3_products.s3_endpoint))
    regexp: ((pipeline_params.s3_products.regexp))

# This task is used in multiple jobs
# The YAML anchor "*prepare-tasks-with-secrets" is used in its place
prepare-tasks-with-secrets: &prepare-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: platform-automation-tasks
    config: configuration
  params:
    CONFIG_PATHS: config/environments/((pipeline_params.iaas))/((pipeline_params.foundation))/config
  output_mapping:
    tasks: platform-automation-tasks

jobs:
- name: first-test-job
  plan:
  - in_parallel:
    - get: configuration

    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["platform-automation-image*"]

    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

    - get: pivnet_product
      trigger: true
      params:
        globs: []  # Only need the metadata - the download-product task will download the product

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: test
    file: platform-automation-tasks/tasks/test.yml
    image: platform-automation-image

  - task: check-pending-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/check-pending-changes.yml
    input_mapping:
      env: configuration
    params:
      ENV_FILE: environments/((pipeline_params.iaas))/((pipeline_params.foundation))/config-director/secrets"
      ALLOW_PENDING_CHANGES: true
