resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: platform-automation

- name: installation
  type: s3
  source:
    endpoint: ((s3_installation_file.endpoint))
    bucket: ((s3_installation_file.bucket))
    access_key_id: ((s3_installation_file.s3_access_key_id))
    secret_access_key: ((s3-secret-access-key))
    regexp: installation-(.*).zip
    disable_ssl: ((s3_installation_file.s3_disable_ssl))
    skip_ssl_verification: ((s3_installation_file.s3_skip_ssl_verification))
    region_name: ((s3_installation_file.region_name))
    use_path_style: true

- name: state
  type: git
  source:
    uri: ((github.repo.uri))
    branch: ((github.repo.branch))
    private_key: ((github-private-key.private-key))


- name: director-configuration
  type: git
  source:
    uri: ((github.repo.uri))
    branch: ((github.repo.branch))
    private_key: ((github-private-key.private-key))
    paths:
    - "environments/((iaas))/((foundation))/config-director"

- name: lock
  type: pool
  source:
    uri: ((github.repo.uri))
    branch: ((github.repo.branch))
    private_key: ((github-private-key.private-key))
    pool: locks/((lock_pool_name))
    retry_delay: 1m

prepare-tasks-with-secrets: &prepare-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: platform-automation-tasks
    config: director-configuration
    vars: director-configuration
  output_mapping:
    tasks: platform-automation-tasks-with-secrets
  params:
    CONFIG_PATHS: |
      config/environments/((iaas))/((foundation))/config-director/templates
      config/environments/((iaas))/((foundation))/common-config
    VARS_PATHS: |
      config/environments/((iaas))/common
      config/environments/((iaas))/((foundation))/config/defaults
      config/environments/((iaas))/((foundation))/config/vars
      config/environments/((iaas))/((foundation))/config/versions

prepare-custom-tasks-with-secrets: &prepare-custom-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: platform-automation-tasks
    config: director-configuration
    vars: director-configuration
  output_mapping:
    tasks: custom-tasks-with-secrets
  params:
    TASK_PARH: tasks/ci/tasks-proposed
    CONFIG_PATHS: |
      config/environments/((iaas))/((foundation))/config-director/templates
      config/environments/((iaas))/((foundation))/common-config
    VARS_PATHS: |
      config/environments/((iaas))/common
      config/environments/((iaas))/((foundation))/config/defaults
      config/environments/((iaas))/((foundation))/config/vars
      config/environments/((iaas))/((foundation))/config/versions

jobs:
- name: force-unlock
  serial: true
  plan:
  - get: lock
  - put: lock
    params:
      release: lock

- name: lock-director
  serial: true
  plan:
  - in_parallel:
    - put: lock
      params: {acquire: true}
    - get: director-configuration
      trigger: true

- name: validate-director-configuration
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
      passed: ["lock-director"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-custom-tasks-with-secrets
    <<: *prepare-custom-tasks-with-secrets

- name: install-opsman
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
      passed: ["validate-director-configuration"]
    - get: state
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-custom-tasks-with-secrets
    <<: *prepare-custom-tasks-with-secrets

  - task: download-create-opsman
    image: platform-automation-image
    file: custom-tasks-with-secrets/ci/tasks-proposed/download-create-opsman.yml
    input_mapping:
      download-config: director-configuration
      state: state
      config: director-configuration
      vars: director-configuration
      secrets: interpolated-files
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/versions/opsman.yml
      STATE_FILE: environments/((iaas))/((foundation))/state/state.yml
      OPSMAN_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/templates/opsman.yml
      VARS_FILES: |
        vars/environments/((iaas))/common-director/opsman.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/infra.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/opsman.yml

    ensure: &make-state-commit
      do:
        - task: make-git-commit
          image: platform-automation-image
          file: custom-tasks-with-secrets/ci/tasks-proposed/z_make-commit.yml
          input_mapping:
            repository: state
            file-source: generated-state
          output_mapping:
            repository-commit: state-commit
          params:
            FILE_SOURCE_PATH: state.yml
            FILE_DESTINATION_PATH: environments/((iaas))/((foundation))/state/state.yml
            GIT_AUTHOR_EMAIL: "tony.elmore@broadcom.com"
            GIT_AUTHOR_NAME: "Platform Automation"
            COMMIT_MESSAGE: 'Update state file'
        - put: state
          params:
            repository: state-commit
            merge: true

  - task: configure-authentication
    image: platform-automation-image
    file: platform-automation-tasks-with-secrets/tasks/configure-authentication.yml
    attempts: 20
    input_mapping:
      env: director-configuration
      config: director-configuration
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
      AUTH_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/secrets/auth.yml

  - task: configure-director
    image: platform-automation-image
    file: platform-automation-tasks-with-secrets/tasks/configure-director.yml
    input_mapping:
      config: director-configuration
      env: director-configuration
      vars: director-configuration
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
      DIRECTOR_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/templates/director.yml
      VARS_FILES: |
        vars/environments/((iaas))/common-director/director.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/infra.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/director.yml
        secrets/environments/((iaas))/((foundation))/config-director/secrets/director.yml

  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks-with-secrets/tasks/apply-director-changes.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml

- name: export-installation
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
      passed: [ install-opsman ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: export-installation
    image: platform-automation-image
    file: platform-automation-tasks-with-secrets/tasks/export-installation.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
  - put: installation
    params:
      file: installation/installation-*.zip

- name: upgrade-opsman
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
      passed: [ export-installation ]
    - get: state
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: installation
      passed: [ export-installation ]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-custom-tasks-with-secrets
    <<: *prepare-custom-tasks-with-secrets

  - task: download-upgrade-opsman
    image: platform-automation-image
    file: custom-tasks-with-secrets/ci/tasks-proposed/download-upgrade-opsman.yml
    input_mapping:
      download-config: director-configuration
      state: state
      config: director-configuration
      vars: director-configuration
      installation: installation
      env: director-configuration
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/versions/opsman.yml
      STATE_FILE: environments/((iaas))/((foundation))/state/state.yml
      OPSMAN_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/templates/opsman.yml
      VARS_FILES: |
        vars/environments/((iaas))/common-director/opsman.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/infra.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/opsman.yml
        secrets/environments/((iaas))/((foundation))/config-director/secrets/opsman.yml
        secrets/environments/((iaas))/((foundation))/config-director/secrets/pivnet.yml
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
    ensure: *make-state-commit

  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks-with-secrets/tasks/apply-director-changes.yml
    input_mapping:
      env: director-configuration
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml

- name: unlock-director
  serial: true
  plan:
  - get: director-configuration
    trigger: true
    passed:
    - "upgrade-opsman"
  - get: lock
  - put: lock
    params:
      release: lock
