resource_types:
- name: pivnet
  type: registry-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    uri: ((pipeline_params.git.uri))
    branch: ((pipeline_params.git.branch))
    private_key: ((github-key.private-key))
    paths:
    - "environments/((iaas))/((foundation))/config"

- name: lock
  type: pool
  source:
    uri: ((pipeline_params.git.uri))
    branch: ((pipeline_params.git.branch))
    private_key: ((github-key.private-key))
    pool: locks/((pipeline_params.lock_pool.name))
    retry_delay: 1m

# Here is the best way I think I can explain prepare-tasks-with-secrets.
# The files in the directories listed in the CONFIG_PATHS will have the secrets defined in them
# Not all of fields need to be from the secret store though (credhub or vault)
# So, if the field will be a var and not a secret, then you need to list the folders that have the vars in them in the VARS_PATHS.
# All of the fields that do not have a var, will be defined as a secret
# The secrets will be set up as environment variables with on OM_ prefix and value from credhub / vault.
# Variables will be passed in to the task as a file
# Then, all of the tasks in the directory listed in the TASK_PATH (at the tasks input_mapping) will be modifed to define
# the the env variables ... that will be put into the output_mapping.
# Therefore, the output_mapping would be used to identify the task when executing the task in the pipeline.

# Here we have a global prepare-tasks-with-secrets that update all of the tasks in the platform-automation-tasks
# Then, we have a prepare-custom-tasks-with-secrets that will update all of the tasks in the ci/tasks-proposed directory
# Finally, a prepare-download-with-secrets that will update all of the tasks in the ci/tasks-proposed directory, but only for the 
# secrets defined in the common-config folder.

# So, maybe it is better to keep the secrets folder with all of the secrets defined for a product, but a folder per product instead of just a file.
# If that is the case, then we wouldn't really use an anchor because the "CONFIG_PATHS" would be different for each product

prepare-tasks-with-secrets: &prepare-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: platform-automation-tasks
    config: configuration
    vars: configuration
  output_mapping:
    tasks: platform-automation-tasks-with-secrets
  params:
    CONFIG_PATHS: |
      config/environments/((iaas))/((foundation))/config/templates
      config/environments/((iaas))/((foundation))/common-config
      config/environments/((iaas))/((foundation))/config/versions
    VARS_PATHS: |
      config/environments/((iaas))/common
      config/environments/((iaas))/((foundation))/config/defaults
      config/environments/((iaas))/((foundation))/config/vars
      config/environments/((iaas))/((foundation))/config/versions

prepare-custom-tasks-with-secrets: &prepare-custom-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: configuration
    config: configuration
    vars: configuration
  output_mapping:
    tasks: custom-tasks-with-secrets
  params:
    TASK_PATH: tasks/ci/tasks-proposed
    CONFIG_PATHS: |
      config/environments/((iaas))/((foundation))/config/templates
      config/environments/((iaas))/((foundation))/common-config
      config/environments/((iaas))/((foundation))/config/versions
    VARS_PATHS: |
      config/environments/((iaas))/common
      config/environments/((iaas))/((foundation))/config/defaults
      config/environments/((iaas))/((foundation))/config/vars
      config/environments/((iaas))/((foundation))/config/versions

prepare-download-with-secrets: &prepare-download-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: configuration
    config: configuration
    vars: configuration
  output_mapping:
    tasks: custom-download-tasks-with-secrets
  params:
    TASK_PATH: tasks/ci/tasks-proposed
    CONFIG_PATHS: |
      config/environments/((iaas))/((foundation))/common-config
    VARS_PATHS: |
      config/environments/((iaas))/common
      config/environments/((iaas))/((foundation))/config/defaults
      config/environments/((iaas))/((foundation))/config/vars
      config/environments/((iaas))/((foundation))/config/versions

jobs:
- name: force-unlock
  serial: true
  plan:
  - get: lock
  - put: lock
    params:
      release: lock

- name: lock-tiles
  serial: true
  plan:
  - in_parallel:
    - put: lock
      params: {acquire: true}
    - get: configuration
      trigger: true

- name: validate-tile-configuration
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: ["lock-tiles"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-custom-tasks-with-secrets
    <<: *prepare-custom-tasks-with-secrets
      
- name: pas
  serial: true
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: [ validate-tile-configuration ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-download-with-secrets
    <<: *prepare-download-with-secrets

  - task: download-stage-tile-stemcell
    image: platform-automation-image
    file: custom-download-tasks-with-secrets/ci/tasks-proposed/download-stage-tile-stemcell.yml
    input_mapping:
      download-config: configuration
      env: configuration
    params:
      PRODUCT_NAME: cf
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf.yml
      DOWNLOAD_STEMCELL_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf-stemcell.yml
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml

  - task: prepare-secrets-for-cf
    image: platform-automation-image
    file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
    input_mapping:
      tasks: platform-automation-tasks
      config: configuration
      vars: configuration
    output_mapping:
      tasks: configure-cf-tasks
    params:
      CONFIG_PATHS: |
        config/environments/((iaas))/((foundation))/common-config
        config/environments/((iaas))/((foundation))/config/secrets/cf
      VARS_PATHS: |
        config/environments/((iaas))/common
        config/environments/((iaas))/((foundation))/config/defaults
        config/environments/((iaas))/((foundation))/config/vars
        config/environments/((iaas))/((foundation))/config/versions

  - task: configure
    image: platform-automation-image
    file: configure-cf-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: configuration
      vars: configuration
      secrets: configuration
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      VARS_FILES: |
        vars/environments/((iaas))/((foundation))/config/defaults/cf.yml
        vars/environments/((iaas))/common/cf.yml
        vars/environments/((iaas))/((foundation))/config/vars/cf.yml
        secrets/environments/((iaas))/((foundation))/config/secrets/cf/cf.yml
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml

# Explain why I had to use configure-cf-tasks instead of platform-automation-tasks-with-secrets for the apply-product-changes task.
  - task: apply-product-changes
    image: platform-automation-image
    file: configure-cf-tasks/tasks/apply-changes.yml
    attempts: 3
    input_mapping:
      env: configuration
    params:
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      SELECTIVE_DEPLOY_PRODUCTS: cf

- name: pas-errands
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: [ pas ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-secrets-for-cf
    image: platform-automation-image
    file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
    input_mapping:
      tasks: platform-automation-tasks
      config: configuration
      vars: configuration
    output_mapping:
      tasks: configure-cf-tasks
    params:
      CONFIG_PATHS: |
        config/environments/((iaas))/((foundation))/common-config
        config/environments/((iaas))/((foundation))/config/secrets/cf
      VARS_PATHS: |
        config/environments/((iaas))/common
        config/environments/((iaas))/((foundation))/config/defaults
        config/environments/((iaas))/((foundation))/config/vars
        config/environments/((iaas))/((foundation))/config/versions

  - task: smoke_tests
    attempts: 5
    image: platform-automation-image
    file: configure-cf-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: cf
      ERRAND_NAME: smoke_tests
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: clock_global/first

  - task: push-usage-service
    attempts: 5
    image: platform-automation-image
    file: configure-cf-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: cf
      ERRAND_NAME: push-usage-service
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: clock_global/first

  - task: push-apps-manager
    attempts: 5
    image: platform-automation-image
    file: configure-cf-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: cf
      ERRAND_NAME: push-apps-manager
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: clock_global/first

  - task: deploy-notifications
    attempts: 5
    image: platform-automation-image
    file: configure-cf-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: cf
      ERRAND_NAME: deploy-notifications
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: clock_global/first

  - task: deploy-notifications-ui
    attempts: 5
    image: platform-automation-image
    file: configure-cf-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: cf
      ERRAND_NAME: deploy-notifications-ui
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: clock_global/first

  - task: deploy-autoscaler
    attempts: 5
    image: platform-automation-image
    file: configure-cf-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: cf
      ERRAND_NAME: deploy-autoscaler
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: clock_global/first

  - task: nfsbrokerpush
    attempts: 5
    image: platform-automation-image
    file: configure-cf-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: cf
      ERRAND_NAME: nfsbrokerpush
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: clock_global/first


- name: pivotal-mysql
  serial: true
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: [ pas ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-download-with-secrets
    <<: *prepare-download-with-secrets

  - task: download-stage-tile-stemcell
    image: platform-automation-image
    file: custom-download-tasks-with-secrets/ci/tasks-proposed/download-stage-tile-stemcell.yml
    input_mapping:
      download-config: configuration
      env: configuration
    params:
      PRODUCT_NAME: pivotal-mysql
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/pivotal-mysql.yml
      DOWNLOAD_STEMCELL_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/pivotal-mysql-stemcell.yml
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml

  - task: prepare-secrets-for-pivotal-mysql
    image: platform-automation-image
    file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
    input_mapping:
      tasks: platform-automation-tasks
      config: configuration
      vars: configuration
    output_mapping:
      tasks: configure-pivotal-mysql-tasks
    params:
      CONFIG_PATHS: |
        config/environments/((iaas))/((foundation))/common-config
        config/environments/((iaas))/((foundation))/config/secrets/pivotal-mysql
      VARS_PATHS: |
        config/environments/((iaas))/common
        config/environments/((iaas))/((foundation))/config/defaults
        config/environments/((iaas))/((foundation))/config/vars
        config/environments/((iaas))/((foundation))/config/versions

  - task: configure
    image: platform-automation-image
    file: configure-pivotal-mysql-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: configuration
      vars: configuration
      secrets: configuration
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/pivotal-mysql.yml
      VARS_FILES: |
        vars/environments/((iaas))/((foundation))/config/defaults/pivotal-mysql.yml
        vars/environments/((iaas))/common/pivotal-mysql.yml
        vars/environments/((iaas))/((foundation))/config/vars/pivotal-mysql.yml
        secrets/environments/((iaas))/((foundation))/config/secrets/pivotal-mysql/pivotal-mysql.yml
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml

# Explain why I had to use configure-pivotal-mysql-tasks instead of platform-automation-tasks-with-secrets for the apply-product-changes task.
  - task: apply-product-changes
    image: platform-automation-image
    file: configure-pivotal-mysql-tasks/tasks/apply-changes.yml
    attempts: 3
    input_mapping:
      env: configuration
    params:
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      SELECTIVE_DEPLOY_PRODUCTS: pivotal-mysql

- name: pivotal-mysql-errands
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: [ pivotal-mysql ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-secrets-for-pivotal-mysql
    image: platform-automation-image
    file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
    input_mapping:
      tasks: platform-automation-tasks
      config: configuration
      vars: configuration
    output_mapping:
      tasks: configure-pivotal-mysql-tasks
    params:
      CONFIG_PATHS: |
        config/environments/((iaas))/((foundation))/common-config
        config/environments/((iaas))/((foundation))/config/secrets/pivotal-mysql
      VARS_PATHS: |
        config/environments/((iaas))/common
        config/environments/((iaas))/((foundation))/config/defaults
        config/environments/((iaas))/((foundation))/config/vars
        config/environments/((iaas))/((foundation))/config/versions

  - task: register-broker
    attempts: 5
    image: platform-automation-image
    file: configure-pivotal-mysql-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: pivotal-mysql
      ERRAND_NAME: register-broker
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: dedicated-mysql-broker/first

  - task: smoke-tests
    attempts: 5
    image: platform-automation-image
    file: configure-pivotal-mysql-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: pivotal-mysql
      ERRAND_NAME: smoke-tests
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: dedicated-mysql-broker/first

  - task: validate-before-upgrade-instances
    attempts: 5
    image: platform-automation-image
    file: configure-pivotal-mysql-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: pivotal-mysql
      ERRAND_NAME: validate-before-upgrade-instances
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: dedicated-mysql-broker/first

  - task: upgrade-all-service-instances 
    attempts: 5
    image: platform-automation-image
    file: configure-pivotal-mysql-tasks/tasks/run-bosh-errand.yml
    input_mapping:
      env: configuration
    params:
      PRODUCT_NAME: pivotal-mysql
      ERRAND_NAME: upgrade-all-service-instances 
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml
      INSTANCE: dedicated-mysql-broker/first

- name: unlock-tile
  serial: true
  plan:
  - get: configuration
    trigger: true
    passed:
    - "pas-errands"
    - "pivotal-mysql-errands"
  - get: lock
  - put: lock
    params:
      release: lock

