resource_types:
- name: pivnet
  type: registry-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    uri: ((pipeline_params.git.uri))
    branch: ((pipeline_params.git.branch))
    private_key: ((github-key.private-key))
    paths:
    - "environments/((iaas))/((foundation))/config"

- name: lock
  type: pool
  source:
    uri: ((pipeline_params.git.uri))
    branch: ((pipeline_params.git.branch))
    private_key: ((github-key.private-key))
    pool: locks/((pipeline_params.lock_pool.name))
    retry_delay: 1m

prepare-tasks-with-secrets: &prepare-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: platform-automation-tasks
    config: configuration
    vars: configuration
  output_mapping:
    tasks: platform-automation-tasks-with-secrets
  params:
    CONFIG_PATHS: |
      config/environments/((iaas))/((foundation))/config/templates
      config/environments/((iaas))/((foundation))/common-config
      config/environments/((iaas))/((foundation))/config/versions
      config/environments/((iaas))/((foundation))/config/secrets
    VARS_PATHS: |
      config/environments/((iaas))/common
      config/environments/((iaas))/((foundation))/config/defaults
      config/environments/((iaas))/((foundation))/config/vars
      config/environments/((iaas))/((foundation))/config/versions

prepare-custom-tasks-with-secrets: &prepare-custom-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: configuration
    config: configuration
    vars: configuration
  output_mapping:
    tasks: custom-tasks-with-secrets
  params:
    TASK_PATH: tasks/ci/tasks-proposed
    CONFIG_PATHS: |
      config/environments/((iaas))/((foundation))/config/templates
      config/environments/((iaas))/((foundation))/common-config
      config/environments/((iaas))/((foundation))/config/versions
      config/environments/((iaas))/((foundation))/config/secrets
    VARS_PATHS: |
      config/environments/((iaas))/common
      config/environments/((iaas))/((foundation))/config/defaults
      config/environments/((iaas))/((foundation))/config/vars
      config/environments/((iaas))/((foundation))/config/versions

jobs:
- name: force-unlock
  serial: true
  plan:
  - get: lock
  - put: lock
    params:
      release: lock

- name: lock-tiles
  serial: true
  plan:
  - in_parallel:
    - put: lock
      params: {acquire: true}
    - get: configuration
      trigger: true

- name: validate-tile-configuration
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: ["lock-tiles"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-custom-tasks-with-secrets
    <<: *prepare-custom-tasks-with-secrets
      
- name: pas
  serial: true
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: [ validate-tile-configuration ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets

  - task: prepare-custom-tasks-with-secrets
    <<: *prepare-custom-tasks-with-secrets

  - task: download-stage-tile-stemcell
    image: platform-automation-image
    file: custom-tasks-with-secrets/ci/tasks-proposed/download-stage-tile-stemcell.yml
    input_mapping:
      download-config: configuration
      env: configuration
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf.yml
      DOWNLOAD_STEMCELL_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf-stemcell.yml
      ENV_FILE: environments/((iaas))/((foundation))/common-config/env.yml

#   - task: configure
#     image: platform-automation-image
#     file: platform-automation-tasks/tasks/configure-product.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#       vars: configuration
#       secrets: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       VARS_FILES: |
#         vars/environments/((iaas))/((foundation))/config/defaults/cf.yml
#         vars/environments/((iaas))/common/cf.yml
#         vars/environments/((iaas))/((foundation))/config/vars/cf.yml
#         secrets/environments/((iaas))/((foundation))/config/secrets/cf.yml
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

#   - task: apply-product-changes
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/apply-product-changes.yml
#     attempts: 10
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

# - name: pas-errands
#   plan:
#   - in_parallel:
#     - get: configuration
#       trigger: true
#       passed: [ pas ]
#     - get: platform-automation-image
#       resource: platform-automation
#       params:
#         unpack: true
#         globs: ["vsphere-platform-automation-image*"]
#     - get: platform-automation-tasks
#       resource: platform-automation
#       params:
#         unpack: true
#         globs: ["*tasks*"]

#   - task: credhub-interpolate
#     image: platform-automation-image
#     file: platform-automation-tasks/tasks/credhub-interpolate.yml
#     params: *credhub_interpolate_params
#     input_mapping:
#       files: configuration

#   - task: smoke_tests
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: smoke_tests
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

#   - task: push-usage-service
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: push-usage-service
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

#   - task: push-apps-manager
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: push-apps-manager
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

#   - task: deploy-notifications
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: deploy-notifications
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

#   - task: deploy-notifications-ui
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: deploy-notifications-ui
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

#   - task: deploy-autoscaler
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: deploy-autoscaler
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

#   - task: nfsbrokerpush
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: nfsbrokerpush
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

#   - task: deploy-notifications-ui
#     attempts: 5
#     image: platform-automation-image
#     file: configuration/ci/tasks-proposed/z_run-errand.yml
#     input_mapping:
#       config: configuration
#       env: interpolated-files
#     params:
#       CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
#       ERRAND_NAME: deploy-notifications-ui
#       ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
#       INSTANCE: clock_global/first

- name: unlock-tile
  serial: true
  plan:
  - get: configuration
    trigger: true
    passed:
    - "pas"
  - get: lock
  - put: lock
    params:
      release: lock

