errand-config:
  delete-all-clusters:
    pre-delete-state: ((delete-all-clusters_pre_delete_state))
  pks-nsx-t-precheck:
    post-deploy-state: ((pks-nsx-t-precheck_post_deploy_state))
  smoke-tests:
    post-deploy-state: ((smoke-tests_post_deploy_state))
  upgrade-all-service-instances:
    post-deploy-state: ((upgrade-all-service-instances_post_deploy_state))
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  - name: ((az2_name))
  - name: ((az3_name))
  service_network:
    name: ((service_network_name))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((pivotal-container-service_pks_tls_certificate))
      private_key_pem: ((pivotal-container-service_pks_tls_privatekey))
  .properties.cloud_provider:
    selected_option: azure
    value: Azure
  .properties.cloud_provider.azure.azure_cloud_name:
    value: ((cloud_provider_azure_azure_cloud_name))
  .properties.cloud_provider.azure.azure_master_managed_identity:
    value: ((cloud_provider_azure_azure_master_managed_identity))
  .properties.cloud_provider.azure.azure_worker_managed_identity:
    value: ((cloud_provider_azure_azure_worker_managed_identity))
  .properties.cloud_provider.azure.default_security_group:
    value: ((cloud_provider_azure_default_security_group))
  .properties.cloud_provider.azure.disable_outbound_snat:
    value: ((cloud_provider_azure_disable_outbound_snat))
  .properties.cloud_provider.azure.location:
    value: ((cloud_provider_azure_location))
  .properties.cloud_provider.azure.primary_availability_set:
    value: ((cloud_provider_azure_primary_availability_set))
  .properties.cloud_provider.azure.resource_group_name:
    value: ((cloud_provider_azure_resource_group_name))
  .properties.cloud_provider.azure.subscription_id:
    value: ((cloud_provider_azure_subscription_id))
  .properties.cloud_provider.azure.tenant_id:
    value: ((cloud_provider_azure_tenant_id))
  .properties.cloud_provider.azure.vnet_name:
    value: ((cloud_provider_azure_vnet_name))
  .properties.cloud_provider.azure.vnet_resource_group_name:
    value: ((cloud_provider_azure_vnet_resource_group_name))
  .properties.log_sink_resources_deploy:
    value: ((log_sink_resources_deploy))
  .properties.metric_sink_resources_deploy:
    value: ((metric_sink_resources_deploy))
  .properties.network_selector:
    value: antrea
  .properties.network_selector.antrea.pod_network_cidr:
    value: ((network_selector_antrea_pod_network_cidr))
  .properties.network_selector.antrea.service_cluster_cidr:
    value: ((network_selector_antrea_service_cluster_cidr))
  .properties.node_exporter_deploy:
    value: ((node_exporter_deploy))
  .properties.oidc_selector:
    value: disabled
  .properties.pks-vrli:
    value: disabled
  .properties.pks-vrops:
    value: disabled
  .properties.pks_api_hostname:
    value: ((pks_api_hostname))
  .properties.plan1_selector:
    value: Plan Active
  .properties.plan1_selector.active.description:
    value: ((plan1_selector_active_description))
  .properties.plan1_selector.active.master_az_placement:
    value: ((plan1_selector_active_master_az_placement))
  .properties.plan1_selector.active.master_instances:
    value: ((plan1_selector_active_master_instances))
  .properties.plan1_selector.active.max_worker_instances:
    value: ((plan1_selector_active_max_worker_instances))
  .properties.plan1_selector.active.name:
    value: ((plan1_selector_active_name))
  .properties.plan1_selector.active.worker_az_placement:
    value: ((plan1_selector_active_worker_az_placement))
  .properties.plan1_selector.active.worker_instances:
    value: ((plan1_selector_active_worker_instances))
  .properties.plan2_selector:
    value: Plan Inactive
  .properties.plan3_selector:
    value: Plan Inactive
  .properties.plan4_selector:
    value: Plan Inactive
  .properties.plan5_selector:
    value: Plan Inactive
  .properties.plan6_selector:
    value: Plan Inactive
  .properties.plan7_selector:
    value: Plan Inactive
  .properties.plan8_selector:
    value: Plan Inactive
  .properties.plan9_selector:
    value: Plan Inactive
  .properties.plan10_selector:
    value: Plan Inactive
  .properties.plan11_selector:
    value: Plan Inactive
  .properties.plan12_selector:
    value: Plan Inactive
  .properties.plan13_selector:
    value: Plan Inactive
  .properties.proxy_selector:
    value: Disabled
  .properties.syslog_selector:
    value: disabled
  .properties.telegraf_selector:
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    selected_option: demo_or_poc
    value: demo_or_poc
  .properties.telemetry_selector:
    value: enabled
  .properties.telemetry_selector.enabled.environment_provider:
    value: ((telemetry_selector_enabled_environment_provider))
  .properties.telemetry_selector.enabled.telemetry_polling_interval:
    value: ((telemetry_selector_enabled_telemetry_polling_interval))
  .properties.telemetry_selector.enabled.telemetry_url:
    value: ((telemetry_selector_enabled_telemetry_url))
  .properties.tmc:
    value: disabled
  .properties.uaa:
    value: internal
  .properties.uaa_pks_cli_access_token_lifetime:
    value: ((uaa_pks_cli_access_token_lifetime))
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: ((uaa_pks_cli_refresh_token_lifetime))
  .properties.uaa_pks_cluster_client_access_token_lifetime:
    value: ((uaa_pks_cluster_client_access_token_lifetime))
  .properties.uaa_pks_cluster_client_refresh_token_lifetime:
    value: ((uaa_pks_cluster_client_refresh_token_lifetime))
  .properties.vsphere_csi:
    value: disabled
  .properties.wavefront:
    value: disabled
  .properties.worker_max_in_flight:
    value: ((worker_max_in_flight))
resource-config:
  pivotal-container-service:
    elb_names: ((resource-var-pivotal-container-service_elb_names))
    instance_type:
      id: ((resource-var-pivotal-container-service_instance_type))
    instances: ((resource-var-pivotal-container-service_instances))
    max_in_flight: ((resource-var-pivotal-container-service_max_in_flight))
    persistent_disk:
      size_mb: ((resource-var-pivotal-container-service_persistent_disk_size))
  pks-db:
    instance_type:
      id: ((resource-var-pks-db_instance_type))
    instances: ((resource-var-pks-db_instances))
    max_in_flight: ((resource-var-pks-db_max_in_flight))
    persistent_disk:
      size_mb: ((resource-var-pks-db_persistent_disk_size))
