# For each task
#   Interpolate all of the parameters 
#   Export the list of parameters
#   Source the task


#   export FOUNDASTION+NAME=blah
#   export WAVEFRONT_AUTOMATION_API_TOKEN = force-unlock
#   source ${task}


---
platform: linux

inputs:
- name: task-repo

params:
  FOUNDATION: 
  PARAM_FILE: 
  VARS_FILES:

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eux

    echo "Pre-configure process started"

    echo "Install yq"
    apt-get -y update && apt-get -y install wget
    wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
    yq -h

    echo "Foundation name is: ${FOUNDATION}"
    echo "Param file is: ${PARAM_FILE}"

    # Get the task name from the param_file
    # The param file should have a task that would be executed

    task="testme.sh"
    SOME_STRING="this is some default string"
    FAIL_FLAG="false"

    cat task-repo/${PARAM_FILE} | yq .

    source task-repo/ci/tasks-proposed/${task}

    echo "Pre-configure process completed"
