resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    branch: master
    password: ((github_token))
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    username: ((github_username))
    paths:
    - "environments/((iaas))/((foundation))/config"

jobs:
- name: pas-errands
  plan:
  - in_parallel:
    - get: configuration
    - get: platform-automation-image  
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"] 
    - get: platform-automation-tasks    
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: 
      CREDHUB_SERVER: ((concourse_credhub_server))
      CREDHUB_CA_CERT: ((concourse_credhub_ca.certificate))
      CREDHUB_CLIENT: ((concourse_credhub_client_username))
      CREDHUB_SECRET: ((concourse_credhub_client_secret))
      PREFIX: '/concourse/((team))'
      INTERPOLATION_PATHS: "environments/((iaas))/((foundation))/config/secrets"
    input_mapping:
      files: configuration

  - across:
    - var: errand_name
      values: [ "smoke_tests", 
                "push-usage-service", 
                "push-apps-manager",
                "deploy-notifications" ]
      # fail_fast: true
    do:
    - task: errand-((.:errand_name))
      attempts: 5
      image: platform-automation-image
      file: configuration/ci/tasks-proposed/z_run-errand.yml
      input_mapping:
        config: configuration
        env: interpolated-files
      params:
        CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
        ERRAND_NAME: ((.:errand_name))
        ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
        INSTANCE: clock_global/first
