errand-config:
  delete-all:
    pre-delete-state: ((delete-all_pre_delete_state))
  deploy-all:
    post-deploy-state: ((deploy-all_post_deploy_state))
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-name: ecs-service-broker
product-properties:
  .properties.broker_certificate_selector:
    value: "No"
  .properties.broker_management_endpoint:
    value: ((broker_management_endpoint))
  .properties.broker_namespace:
    value: ((broker_namespace))
  .properties.broker_password:
    value:
      secret: ((broker_password))
  .properties.broker_path_style_access:
    value: ((broker_path_style_access))
  .properties.broker_replication_group:
    value: ((broker_replication_group))
  .properties.broker_use_ssl:
    value: ((broker_use_ssl))
  .properties.broker_username:
    value: ((broker_username))
  .properties.catalog_plan_collection0:
    value:
    - access_during_outage: ((catalog_plan_collection0_0_access_during_outage))
      bucket_tags: ((catalog_plan_collection0_0_bucket_tags))
      bullet_1: Shared Object Storage
      bullet_2: 5 GB Storage Limit
      bullet_3: S3 Protocol Access
      bullet_4: ((catalog_plan_collection0_0_bullet_4))
      bullet_5: ((catalog_plan_collection0_0_bullet_5))
      cost_currency: USD
      cost_unit: MONTHLY
      cost_value: 0
      default_retention: ((catalog_plan_collection0_0_default_retention))
      description: 5 GB free trial
      free: true
      name: 5gb
      namespace: ((catalog_plan_collection0_0_namespace))
      quota_limit: 5
      quota_warn: 4
      replication_group: ((catalog_plan_collection0_0_replication_group))
      repository_plan: ((catalog_plan_collection0_0_repository_plan))
    - access_during_outage: ((catalog_plan_collection0_0_access_during_outage))
      bucket_tags: ((catalog_plan_collection0_0_bucket_tags))
      bullet_1: Shared Object Storage
      bullet_2: Unlimited Storage
      bullet_3: S3 Protocol Access
      bullet_4: ((catalog_plan_collection0_0_bullet_4))
      bullet_5: ((catalog_plan_collection0_0_bullet_5))
      cost_currency: USD
      cost_unit: PER_GB_PER_MONTH
      cost_value: 0.03
      default_retention: ((catalog_plan_collection0_0_default_retention))
      description: Usage based billing
      free: ((catalog_plan_collection0_0_free))
      name: unlimited
      namespace: ((catalog_plan_collection0_0_namespace))
      quota_limit: ((catalog_plan_collection0_0_quota_limit))
      quota_warn: ((catalog_plan_collection0_0_quota_warn))
      replication_group: ((catalog_plan_collection0_0_replication_group))
      repository_plan: true
  .properties.catalog_plan_collection1:
    value:
    - access_during_outage: ((catalog_plan_collection1_0_access_during_outage))
      bucket_tags: ((catalog_plan_collection1_0_bucket_tags))
      bullet_1: Shared Object Storage
      bullet_2: 5 GB Storage Limit
      bullet_3: S3 Protocol Access
      bullet_4: ((catalog_plan_collection1_0_bullet_4))
      bullet_5: ((catalog_plan_collection1_0_bullet_5))
      cost_currency: USD
      cost_unit: MONTHLY
      cost_value: 0
      default_retention: ((catalog_plan_collection1_0_default_retention))
      description: 5 GB free trial
      free: true
      name: 5gb
      namespace: ((catalog_plan_collection1_0_namespace))
      quota_limit: 5
      quota_warn: 4
      replication_group: ((catalog_plan_collection1_0_replication_group))
      repository_plan: ((catalog_plan_collection1_0_repository_plan))
    - access_during_outage: ((catalog_plan_collection1_0_access_during_outage))
      bucket_tags: ((catalog_plan_collection1_0_bucket_tags))
      bullet_1: Shared Object Storage
      bullet_2: Unlimited Storage
      bullet_3: S3 Protocol Access
      bullet_4: ((catalog_plan_collection1_0_bullet_4))
      bullet_5: ((catalog_plan_collection1_0_bullet_5))
      cost_currency: USD
      cost_unit: PER_GB_PER_MONTH
      cost_value: 0.03
      default_retention: ((catalog_plan_collection1_0_default_retention))
      description: Usage based billing
      free: ((catalog_plan_collection1_0_free))
      name: unlimited
      namespace: ((catalog_plan_collection1_0_namespace))
      quota_limit: ((catalog_plan_collection1_0_quota_limit))
      quota_warn: ((catalog_plan_collection1_0_quota_warn))
      replication_group: ((catalog_plan_collection1_0_replication_group))
      repository_plan: true
  .properties.catalog_service_settings0:
    value: Bucket
  .properties.catalog_service_settings0.bucket_option.encrypted:
    value: ((catalog_service_settings0_bucket_option_encrypted))
  .properties.catalog_service_settings0.bucket_option.file_accessible:
    value: ((catalog_service_settings0_bucket_option_file_accessible))
  .properties.catalog_service_settings0.bucket_option.head_type:
    value: ((catalog_service_settings0_bucket_option_head_type))
  .properties.catalog_service_settings1:
    value: Namespace
  .properties.catalog_service_settings1.namespace_option.compliance_enabled:
    value: ((catalog_service_settings1_namespace_option_compliance_enabled))
  .properties.catalog_service_settings1.namespace_option.encrypted:
    value: ((catalog_service_settings1_namespace_option_encrypted))
  .properties.catalog_service_settings2:
    value: Bucket
  .properties.catalog_service_settings2.bucket_option.encrypted:
    value: ((catalog_service_settings2_bucket_option_encrypted))
  .properties.catalog_service_settings2.bucket_option.file_accessible:
    value: ((catalog_service_settings2_bucket_option_file_accessible))
  .properties.catalog_service_settings2.bucket_option.head_type:
    value: ((catalog_service_settings2_bucket_option_head_type))
  .properties.catalog_service_settings3:
    value: Bucket
  .properties.catalog_service_settings3.bucket_option.encrypted:
    value: ((catalog_service_settings3_bucket_option_encrypted))
  .properties.catalog_service_settings3.bucket_option.file_accessible:
    value: ((catalog_service_settings3_bucket_option_file_accessible))
  .properties.catalog_service_settings3.bucket_option.head_type:
    value: ((catalog_service_settings3_bucket_option_head_type))
  .properties.catalog_service_settings4:
    value: Bucket
  .properties.catalog_service_settings4.bucket_option.encrypted:
    value: ((catalog_service_settings4_bucket_option_encrypted))
  .properties.catalog_service_settings4.bucket_option.file_accessible:
    value: ((catalog_service_settings4_bucket_option_file_accessible))
  .properties.catalog_service_settings4.bucket_option.head_type:
    value: ((catalog_service_settings4_bucket_option_head_type))
  .properties.catalog_services_0_active:
    value: ((catalog_services_0_active))
  .properties.catalog_services_0_bindable:
    value: ((catalog_services_0_bindable))
  .properties.catalog_services_0_description:
    value: ((catalog_services_0_description))
  .properties.catalog_services_0_display_name:
    value: ((catalog_services_0_display_name))
  .properties.catalog_services_0_documentation_url:
    value: ((catalog_services_0_documentation_url))
  .properties.catalog_services_0_image_url:
    value: ((catalog_services_0_image_url))
  .properties.catalog_services_0_long_description:
    value: ((catalog_services_0_long_description))
  .properties.catalog_services_0_name:
    value: ((catalog_services_0_name))
  .properties.catalog_services_0_provider_display_name:
    value: ((catalog_services_0_provider_display_name))
  .properties.catalog_services_0_repository_service:
    value: ((catalog_services_0_repository_service))
  .properties.catalog_services_0_support_url:
    value: ((catalog_services_0_support_url))
  .properties.catalog_services_0_tags:
    value: ((catalog_services_0_tags))
  .properties.catalog_services_1_active:
    value: ((catalog_services_1_active))
  .properties.catalog_services_1_bindable:
    value: ((catalog_services_1_bindable))
  .properties.catalog_services_1_description:
    value: ((catalog_services_1_description))
  .properties.catalog_services_1_display_name:
    value: ((catalog_services_1_display_name))
  .properties.catalog_services_1_documentation_url:
    value: ((catalog_services_1_documentation_url))
  .properties.catalog_services_1_image_url:
    value: ((catalog_services_1_image_url))
  .properties.catalog_services_1_long_description:
    value: ((catalog_services_1_long_description))
  .properties.catalog_services_1_name:
    value: ((catalog_services_1_name))
  .properties.catalog_services_1_provider_display_name:
    value: ((catalog_services_1_provider_display_name))
  .properties.catalog_services_1_repository_service:
    value: ((catalog_services_1_repository_service))
  .properties.catalog_services_1_support_url:
    value: ((catalog_services_1_support_url))
  .properties.catalog_services_1_tags:
    value: ((catalog_services_1_tags))
  .properties.catalog_services_2_active:
    value: ((catalog_services_2_active))
  .properties.catalog_services_2_bindable:
    value: ((catalog_services_2_bindable))
  .properties.catalog_services_2_description:
    value: ((catalog_services_2_description))
  .properties.catalog_services_2_display_name:
    value: ((catalog_services_2_display_name))
  .properties.catalog_services_2_documentation_url:
    value: ((catalog_services_2_documentation_url))
  .properties.catalog_services_2_image_url:
    value: ((catalog_services_2_image_url))
  .properties.catalog_services_2_long_description:
    value: ((catalog_services_2_long_description))
  .properties.catalog_services_2_name:
    value: ((catalog_services_2_name))
  .properties.catalog_services_2_provider_display_name:
    value: ((catalog_services_2_provider_display_name))
  .properties.catalog_services_2_repository_service:
    value: ((catalog_services_2_repository_service))
  .properties.catalog_services_2_support_url:
    value: ((catalog_services_2_support_url))
  .properties.catalog_services_2_tags:
    value: ((catalog_services_2_tags))
  .properties.catalog_services_3_active:
    value: ((catalog_services_3_active))
  .properties.catalog_services_3_bindable:
    value: ((catalog_services_3_bindable))
  .properties.catalog_services_3_description:
    value: ((catalog_services_3_description))
  .properties.catalog_services_3_display_name:
    value: ((catalog_services_3_display_name))
  .properties.catalog_services_3_documentation_url:
    value: ((catalog_services_3_documentation_url))
  .properties.catalog_services_3_image_url:
    value: ((catalog_services_3_image_url))
  .properties.catalog_services_3_long_description:
    value: ((catalog_services_3_long_description))
  .properties.catalog_services_3_name:
    value: ((catalog_services_3_name))
  .properties.catalog_services_3_provider_display_name:
    value: ((catalog_services_3_provider_display_name))
  .properties.catalog_services_3_repository_service:
    value: ((catalog_services_3_repository_service))
  .properties.catalog_services_3_support_url:
    value: ((catalog_services_3_support_url))
  .properties.catalog_services_3_tags:
    value: ((catalog_services_3_tags))
  .properties.catalog_services_4_active:
    value: ((catalog_services_4_active))
  .properties.catalog_services_4_bindable:
    value: ((catalog_services_4_bindable))
  .properties.catalog_services_4_description:
    value: ((catalog_services_4_description))
  .properties.catalog_services_4_display_name:
    value: ((catalog_services_4_display_name))
  .properties.catalog_services_4_documentation_url:
    value: ((catalog_services_4_documentation_url))
  .properties.catalog_services_4_image_url:
    value: ((catalog_services_4_image_url))
  .properties.catalog_services_4_long_description:
    value: ((catalog_services_4_long_description))
  .properties.catalog_services_4_name:
    value: ((catalog_services_4_name))
  .properties.catalog_services_4_provider_display_name:
    value: ((catalog_services_4_provider_display_name))
  .properties.catalog_services_4_repository_service:
    value: ((catalog_services_4_repository_service))
  .properties.catalog_services_4_support_url:
    value: ((catalog_services_4_support_url))
  .properties.catalog_services_4_tags:
    value: ((catalog_services_4_tags))
  .properties.ecs_broker_enable_global_access_to_plans:
    value: ((ecs_broker_enable_global_access_to_plans))
resource-config:
  delete-all:
    instance_type:
      id: ((resource-var-delete-all_instance_type))
    max_in_flight: ((resource-var-delete-all_max_in_flight))
  deploy-all:
    instance_type:
      id: ((resource-var-deploy-all_instance_type))
    max_in_flight: ((resource-var-deploy-all_max_in_flight))
