---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 5\..*

- name: jq
  type: github-release
  check_every: 372h
  source:
    owner: stedolan
    repository: jq

- name: ops-manager
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: ((ops-manager_version_regex))

- name: cf
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ((cf_version_regex))

- name: twistlock
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: twistlock
    product_version: ((twistlock_version_regex))

- name: ipsec
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: p-ipsec-addon
    product_version: ((ipsec_version_regex))

- name: stemcell-jammy-1
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: stemcells-ubuntu-jammy
    product_version: ^1\..*

- name: source
  type: git
  source:
    branch: master
    password: ((github_token))
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    username: ((github_username))
    paths:
    - "environments/((iaas))/mgmt-pipelines/get-latest-version-config.yml"
    
jobs:
- name: validate-secrets
  plan:
  - in_parallel:
    - get: source
      trigger: true
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: &credhub_interpolate_params
      CREDHUB_SERVER: ((concourse_credhub_server))
      CREDHUB_CA_CERT: ((concourse_credhub_ca.certificate))
      CREDHUB_CLIENT: ((concourse_credhub_client_username))
      CREDHUB_SECRET: ((concourse_credhub_client_secret))
      PREFIX: '/concourse/((team))'
      INTERPOLATION_PATHS: "environments/((iaas))/mgmt-pipelines/secrets"
    input_mapping:
      files: source

- name: update-ops-manager
  serial: true
  plan:
  - in_parallel:
    - get: source
      trigger: true
      passed: ["validate-secrets"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: ops-manager
      params:
        globs: [] # Only need the metadata
    - get: jq
      params:
        globs: [jq-linux64]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: source

  - task: update-product-version
    file: source/ci/tasks-proposed/update-product-version.yml
    image: platform-automation-image
    input_mapping:
      product: ops-manager
      env: interpolated-files
    params:
      PRODUCT_NAME: opsman
      PRODUCT_SLUG: ops-manager
      ENV_FILE: environments/((iaas))/mgmt-pipelines/secrets/env.yml


- name: update-cf
  serial: true
  plan:
  - in_parallel:
    - get: source
      trigger: true
      passed: ["update-ops-manager"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: stemcell-jammy-1
      params:
        globs: []
    - get: cf
      params:
        globs: [] # Only need the metadata
    - get: jq
      params:
        globs: [jq-linux64]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: source

  - task: update-product-version
    file: source/ci/tasks-proposed/update-product-version.yml
    image: platform-automation-image
    input_mapping:
      product: cf
      env: interpolated-files
    params:
      PRODUCT_NAME: cf
      PRODUCT_SLUG: elastic-runtime
      ENV_FILE: environments/((iaas))/mgmt-pipelines/secrets/env.yml

- name: update-twistlock
  serial: true
  plan:
  - in_parallel:
    - get: source
      trigger: true
      passed: ["update-cf"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: stemcell-jammy-1
      params:
        globs: []
    - get: twistlock
      params:
        globs: [] # Only need the metadata
    - get: jq
      params:
        globs: [jq-linux64]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: source

  - task: update-product-version
    file: source/ci/tasks-proposed/update-product-version.yml
    image: platform-automation-image
    input_mapping:
      product: twistlock
      env: interpolated-files
    params:
      PRODUCT_NAME: twistlock
      PRODUCT_SLUG: twistlock
      ENV_FILE: environments/((iaas))/mgmt-pipelines/secrets/env.yml

- name: update-ipsec
  serial: true
  plan:
  - in_parallel:
    - get: source
      trigger: true
      passed: ["update-cf"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: stemcell-jammy-1
      params:
        globs: []
    - get: ipsec
      params:
        globs: [] # Only need the metadata
    - get: jq
      params:
        globs: [jq-linux64]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: source

  - task: update-product-version
    file: source/ci/tasks-proposed/update-product-version.yml
    image: platform-automation-image
    input_mapping:
      product: ipsec
      env: interpolated-files
    params:
      PRODUCT_NAME: ipsec
      PRODUCT_SLUG: p-ipsec-addon
      ENV_FILE: environments/((iaas))/mgmt-pipelines/secrets/env.yml
