---
opsman-configuration:
  vsphere:
    vcenter:
      datacenter: ((vcenter_datacenter))
      datastore: ((vcenter_datastore))
      folder: ((ops_manager_folder))
      url: ((vcenter_host))
      username: ((vcenter_username))
      password: ((vcenter_password))
      resource_pool: /((vcenter_datacenter))/host/((vcenter_cluster))/Resources/((vcenter_resource_pool))
      insecure: ((allow_unverified_ssl))
    disk_type: thin
    dns: ((ops_manager_dns_servers))
    gateway: ((concourse_subnet_gateway))
    hostname: ((ops_manager_dns))
    netmask: ((ops_manager_netmask))
    network: ((concourse_subnet_name))
    ntp: ((ops_manager_ntp))
    private_ip: ((ops_manager_private_ip))
    ssh_public_key: ((ops_manager_ssh_public_key))
#    vm_name: ((opsman_vm_name))
