---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "healthwatch-pas-exporter*.pivotal"
pivnet-product-slug: "p-healthwatch"
product-version: "2.0.5"

# Use these vars when pulling from azure blobstore
# azure-storage-account: telmoreprodandstemcell
# azure-storage-key: ((azure-storage-key))
# blobstore-bucket: productstorage