log_sink_resources_deploy: true
metric_sink_resources_deploy: true
network_selector_antrea_pod_network_cidr: 10.200.0.0/16
network_selector_antrea_service_cluster_cidr: 10.100.200.0/24
node_exporter_deploy: false
plan1_selector_active_allow_privileged_containers: false
plan1_selector_active_description: 'Example: This plan will configure a lightweight
  kubernetes cluster. Not recommended for production workloads.'
plan1_selector_active_kubelet_drain_delete_local_data: true
plan1_selector_active_kubelet_drain_force: true
plan1_selector_active_kubelet_drain_force_node: false
plan1_selector_active_kubelet_drain_grace_period: 10
plan1_selector_active_kubelet_drain_ignore_daemonsets: true
plan1_selector_active_kubelet_drain_timeout: 0
plan1_selector_active_master_instances: 1
plan1_selector_active_max_worker_instances: 50
plan1_selector_active_name: small
plan1_selector_active_worker_instances: 3
telemetry_selector_enabled_environment_provider: none
telemetry_selector_enabled_telemetry_polling_interval: 21600
telemetry_selector_enabled_telemetry_url: https://vcsa.vmware.com/ph
uaa_pks_cli_access_token_lifetime: 600
uaa_pks_cli_refresh_token_lifetime: 21600
uaa_pks_cluster_client_access_token_lifetime: 600
uaa_pks_cluster_client_refresh_token_lifetime: 21600
worker_max_in_flight: 4
delete-all-clusters_pre_delete_state: default
pks-nsx-t-precheck_post_deploy_state: default
smoke-tests_post_deploy_state: default
upgrade-all-service-instances_post_deploy_state: default
resource-var-pivotal-container-service_instance_type: automatic
resource-var-pivotal-container-service_instances: automatic
resource-var-pivotal-container-service_max_in_flight: default
resource-var-pivotal-container-service_persistent_disk_size: automatic
resource-var-pks-db_instance_type: automatic
resource-var-pks-db_instances: automatic
resource-var-pks-db_max_in_flight: default
resource-var-pks-db_persistent_disk_size: automatic
