credhub_internal_provider_keys_0_key: ((credhub_key_encryption_password))
credhub_internal_provider_keys_0_name: key

networking_poe_ssl_certs_0_certificate: ((pas_network_cert.certificate))
networking_poe_ssl_certs_0_name: router-cert
networking_poe_ssl_certs_0_privatekey: ((pas_network_cert.private_key))

# credhub_hsm_provider_client_certificate_certificate: ((credhub_hsm_provider_client.certificate))
# credhub_hsm_provider_client_certificate_privatekey: ((credhub_hsm_provider_client.private_key))

uaa_service_provider_key_credentials_certificate: ((uaa_service_provider_key_credentials.certificate))
uaa_service_provider_key_credentials_privatekey: ((uaa_service_provider_key_credentials.private_key))

# This value is from the director credhub (-n /services/tls_ca) and is used as the trusted certs for director
# Adding here so that CloudCache would work
# However, there may be other trusted certs for the director which means this may need to be a credhub
# entry for PAS only at some point
# routing_custom_ca_certificates: ((director_trusted_cert.certificate))