broker_path_style_access: true
broker_use_ssl: false
catalog_plan_collection0_0_access_during_outage: true
catalog_plan_collection1_0_access_during_outage: true
catalog_plan_collection2_0_access_during_outage: true
catalog_plan_collection3_0_access_during_outage: true
catalog_plan_collection4_0_access_during_outage: true
catalog_service_settings0_bucket_option_encrypted: false
catalog_service_settings0_bucket_option_file_accessible: false
catalog_service_settings0_bucket_option_head_type: s3
catalog_service_settings1_namespace_option_compliance_enabled: false
catalog_service_settings1_namespace_option_encrypted: false
catalog_service_settings2_bucket_option_encrypted: false
catalog_service_settings2_bucket_option_file_accessible: true
catalog_service_settings2_bucket_option_head_type: s3
catalog_service_settings3_bucket_option_encrypted: false
catalog_service_settings3_bucket_option_file_accessible: false
catalog_service_settings3_bucket_option_head_type: s3
catalog_service_settings4_bucket_option_encrypted: false
catalog_service_settings4_bucket_option_file_accessible: false
catalog_service_settings4_bucket_option_head_type: s3
catalog_services_0_active: true
catalog_services_0_bindable: true
catalog_services_0_description: Dell EMC ECS private object storage bucket
catalog_services_0_display_name: ECS Bucket
catalog_services_0_documentation_url: https://community.emc.com/docs/DOC-45012
catalog_services_0_image_url: https://avatars.githubusercontent.com/u/12926680
catalog_services_0_long_description: Dell EMC Elastic Cloud Storage (ECS) private
  object storage Bucket
catalog_services_0_name: ecs-bucket
catalog_services_0_provider_display_name: Dell EMC
catalog_services_0_repository_service: true
catalog_services_0_support_url: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
catalog_services_0_tags: s3,bucket
catalog_services_1_active: false
catalog_services_1_bindable: true
catalog_services_1_description: Dell EMC ECS private object storage namespace
catalog_services_1_display_name: ECS Namespace
catalog_services_1_documentation_url: https://community.emc.com/docs/DOC-45012
catalog_services_1_image_url: https://avatars.githubusercontent.com/u/12926680
catalog_services_1_long_description: Dell EMC Elastic Cloud Storage (ECS) private
  object storage Namespace
catalog_services_1_name: ecs-namespace
catalog_services_1_provider_display_name: Dell EMC
catalog_services_1_repository_service: false
catalog_services_1_support_url: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
catalog_services_1_tags: s3,namespace
catalog_services_2_active: false
catalog_services_2_bindable: true
catalog_services_2_description: Dell EMC ECS private object storage bucket with file
  support
catalog_services_2_display_name: ECS File-Enabled Bucket
catalog_services_2_documentation_url: https://community.emc.com/docs/DOC-45012
catalog_services_2_image_url: https://avatars.githubusercontent.com/u/12926680
catalog_services_2_long_description: Dell EMC Elastic Cloud Storage (ECS) object storage
  bucket with support for file protocols. Supports S3, NFS and HDFS access.
catalog_services_2_name: ecs-file-bucket
catalog_services_2_provider_display_name: Dell EMC
catalog_services_2_repository_service: true
catalog_services_2_support_url: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
catalog_services_2_tags: s3,bucket,nfs,hdfs
catalog_services_3_active: false
catalog_services_3_bindable: true
catalog_services_3_description: Dell EMC ECS private object storage bucket
catalog_services_3_display_name: ECS Bucket
catalog_services_3_documentation_url: https://community.emc.com/docs/DOC-45012
catalog_services_3_image_url: https://avatars.githubusercontent.com/u/12926680
catalog_services_3_long_description: Dell EMC Elastic Cloud Storage (ECS) private
  object storage Bucket
catalog_services_3_name: ecs-bucket
catalog_services_3_provider_display_name: Dell EMC
catalog_services_3_repository_service: true
catalog_services_3_support_url: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
catalog_services_3_tags: s3,bucket
catalog_services_4_active: false
catalog_services_4_bindable: true
catalog_services_4_description: Dell EMC ECS private object storage bucket
catalog_services_4_display_name: ECS Bucket
catalog_services_4_documentation_url: https://community.emc.com/docs/DOC-45012
catalog_services_4_image_url: https://avatars.githubusercontent.com/u/12926680
catalog_services_4_long_description: Dell EMC Elastic Cloud Storage (ECS) private
  object storage Bucket
catalog_services_4_name: ecs-bucket
catalog_services_4_provider_display_name: Dell EMC
catalog_services_4_repository_service: true
catalog_services_4_support_url: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
catalog_services_4_tags: s3,bucket
ecs_broker_enable_global_access_to_plans: (( .properties.enable_global_access_to_plans.value
  ))
delete-all_pre_delete_state: default
deploy-all_post_deploy_state: default
resource-var-delete-all_instance_type: automatic
resource-var-delete-all_max_in_flight: default
resource-var-deploy-all_instance_type: automatic
resource-var-deploy-all_max_in_flight: default
