default_distributed_system_id: 0
dev_plan_enable_service_plan_enable_cf_service_access: enable
dev_plan_enable_service_plan_enable_plan_description: Plan Description
dev_plan_enable_service_plan_enable_plan_name: dev-plan
dev_plan_enable_service_plan_enable_service_instance_quota: 10
dev_plan_enable_service_plan_enable_service_metrics: true
enable_secure_binding: false
number_simultaneous_upgrades: 1
number_upgrade_canary_instances: 0
plan1_enable_service_plan_enable_cf_service_access: enable
plan1_enable_service_plan_enable_default_num_servers: 4
plan1_enable_service_plan_enable_max_servers_per_cluster: 32
plan1_enable_service_plan_enable_plan_description: Plan Description
plan1_enable_service_plan_enable_plan_name: extra-small
plan1_enable_service_plan_enable_service_instance_quota: 10
plan1_enable_service_plan_enable_service_metrics: true
plan2_enable_service_plan_enable_cf_service_access: enable
plan2_enable_service_plan_enable_default_num_servers: 4
plan2_enable_service_plan_enable_max_servers_per_cluster: 32
plan2_enable_service_plan_enable_plan_description: Plan Description
plan2_enable_service_plan_enable_plan_name: small
plan2_enable_service_plan_enable_service_instance_quota: 10
plan2_enable_service_plan_enable_service_metrics: true
plan3_enable_service_plan_enable_cf_service_access: enable
plan3_enable_service_plan_enable_default_num_servers: 4
plan3_enable_service_plan_enable_max_servers_per_cluster: 32
plan3_enable_service_plan_enable_plan_description: Plan Description
plan3_enable_service_plan_enable_plan_name: medium
plan3_enable_service_plan_enable_service_instance_quota: 10
plan3_enable_service_plan_enable_service_metrics: true
plan4_enable_service_plan_enable_cf_service_access: enable
plan4_enable_service_plan_enable_default_num_servers: 4
plan4_enable_service_plan_enable_max_servers_per_cluster: 32
plan4_enable_service_plan_enable_plan_description: Plan Description
plan4_enable_service_plan_enable_plan_name: large
plan4_enable_service_plan_enable_service_instance_quota: 10
plan4_enable_service_plan_enable_service_metrics: true
plan5_enable_service_plan_enable_cf_service_access: enable
plan5_enable_service_plan_enable_default_num_servers: 4
plan5_enable_service_plan_enable_max_servers_per_cluster: 32
plan5_enable_service_plan_enable_plan_description: Plan Description
plan5_enable_service_plan_enable_plan_name: extra-large
plan5_enable_service_plan_enable_service_instance_quota: 10
plan5_enable_service_plan_enable_service_metrics: true
small_footprint_enable_service_plan_enable_cf_service_access: enable
small_footprint_enable_service_plan_enable_max_servers_per_cluster: 32
small_footprint_enable_service_plan_enable_plan_description: Plan Description
small_footprint_enable_service_plan_enable_plan_name: small-footprint
small_footprint_enable_service_plan_enable_service_instance_quota: 10
small_footprint_enable_service_plan_enable_service_metrics: true
delete-all-service-instances-and-deregister-broker_pre_delete_state: default
register-broker_post_deploy_state: default
smoke-tests_post_deploy_state: default
upgrade-all-service-instances_post_deploy_state: default
resource-var-cloudcache-broker_instance_type: automatic
resource-var-cloudcache-broker_max_in_flight: default
resource-var-cloudcache-broker_persistent_disk_size: automatic
resource-var-sni-tcp-router_instance_type: automatic
resource-var-sni-tcp-router_instances: automatic
resource-var-sni-tcp-router_max_in_flight: default
