healthwatch-forwarder_boshhealth_instance_count: 1
healthwatch-forwarder_boshtasks_instance_count: 2
healthwatch-forwarder_canary_instance_count: 2
healthwatch-forwarder_cli_instance_count: 2
healthwatch-forwarder_ingestor_instance_count: 4
healthwatch-forwarder_opsman_instance_count: 2
healthwatch-forwarder_publish_to_eva: true
healthwatch-forwarder_push_apps_in_parallel: true
healthwatch-forwarder_worker_instance_count: 1
cleanup_pre_delete_state: default
push-apps_post_deploy_state: default
smoke-tests_post_deploy_state: default
validate-expected-metrics_post_deploy_state: default
resource-var-healthwatch-forwarder_instance_type: automatic
resource-var-healthwatch-forwarder_instances: automatic
resource-var-healthwatch-forwarder_max_in_flight: default
resource-var-healthwatch-forwarder_persistent_disk_size: automatic
resource-var-mysql_instance_type: automatic
resource-var-mysql_instances: automatic
resource-var-mysql_max_in_flight: default
resource-var-mysql_persistent_disk_size: automatic
resource-var-redis_instance_type: automatic
resource-var-redis_instances: automatic
resource-var-redis_max_in_flight: default
resource-var-redis_persistent_disk_size: automatic
