buildpack: java_buildpack_offline
deploy-service-broker_post_deploy_state: default
destroy-broker_pre_delete_state: default
resource-var-deploy-service-broker_instance_type: automatic
resource-var-deploy-service-broker_max_in_flight: default
resource-var-destroy-broker_instance_type: automatic
resource-var-destroy-broker_max_in_flight: default
