default_running_asg_use_ip_set: false
enable_inventory: true
enable_snat: true
master_timeout: 18
ncp_debug_log: false
nsx_node_agent_debug_log: false
subnet_prefix: 24
wait_for_security_policy_sync: false
