plan1_selector_single_node_az_multi_select: ["zone-1"]
plan2_selector_single_node_az_multi_select: ["zone-1"]
plan3_selector_single_node_az_multi_select: ["zone-1"]

backups_selector_azure_account: 0xt84e0fox1z6drulfdc
backups_selector_azure_container: "mysql-backups"
backups_selector_azure_cron_schedule: "0 */8 * * *"
