---
name: emptyvm-sabd

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

releases: []

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: emptyvm-sabd
  azs: [az1]
  instances: 1
  jobs: []
  vm_type: large.disk
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: deployment
