jobs:
- name: test-job
  plan:
  - task: display-cred
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      run:
        path: bash
        args: [-c, 'echo test value: $test_value']
    params:
      test_value: ((testvalue))