resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    branch: master
    password: ((github_token))
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    username: ((github_username))
    paths:
    - "environments/((iaas))/((foundation))/pipeline-products.yml"
    - "environments/((iaas))/((foundation))/config"

- name: lock
  type: pool
  source:
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    branch: master
    username: ((github_username))
    password: ((github_token))
    pool: locks/((lock_pool_name))
    retry_delay: 1m

jobs:
- name: force-unlock
  serial: true
  plan:
  - get: lock
  - put: lock
    params:
      release: lock

- name: lock-tiles
  serial: true
  plan:
  - aggregate:
    - put: lock
      params: {acquire: true}
    - get: configuration
      trigger: true

- name: validate-tile-configuration
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      passed: ["lock-tiles"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: &credhub_interpolate_params
      CREDHUB_SERVER: https://concourse.haas-424.pez.vmware.com:8844
      CREDHUB_CA_CERT: ((concourse_credhub_ca.certificate))
      CREDHUB_CLIENT: ((concourse_credhub_client_username))
      CREDHUB_SECRET: ((concourse_credhub_client_secret))
      PREFIX: '/concourse/((team))'
      INTERPOLATION_PATHS: "environments/((iaas))/((foundation))/config/secrets"
    input_mapping:
      files: configuration

- name: pas
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      passed: [ validate-tile-configuration ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: configuration

  - task: download-stage-tile-stemcell-nsx-t
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/download-stage-tile-stemcell.yml
    input_mapping:
      config: configuration
      download-config: configuration
      env: interpolated-files
      secrets: interpolated-files
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/vmware-nsx-t.yml
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/vmware-nsx-t.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      VARS_FILES: secrets/environments/((iaas))/((foundation))/config/secrets/pivnet.yml

  - task: download-stage-tile-stemcell
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/download-stage-tile-stemcell.yml
    input_mapping:
      config: configuration
      download-config: configuration
      env: interpolated-files
      secrets: interpolated-files
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf.yml
      DOWNLOAD_STEMCELL_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf-stemcell.yml
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      VARS_FILES: secrets/environments/((iaas))/((foundation))/config/secrets/pivnet.yml

  - task: configure-nsx
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: interpolated-files
      vars: configuration
      secrets: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/vmware-nsx-t.yml
      VARS_FILES: |
        vars/environments/((iaas))/((foundation))/config/defaults/vmware-nsx-t.yml
        vars/environments/((iaas))/common/vmware-nsx-t.yml
        vars/environments/((iaas))/((foundation))/config/vars/vmware-nsx-t.yml
        secrets/environments/((iaas))/((foundation))/config/secrets/vmware-nsx-t.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

  - task: configure
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: interpolated-files
      vars: configuration
      secrets: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      VARS_FILES: |
        vars/environments/((iaas))/((foundation))/config/defaults/cf.yml
        vars/environments/((iaas))/common/cf.yml
        vars/environments/((iaas))/((foundation))/config/vars/cf.yml
        secrets/environments/((iaas))/((foundation))/config/secrets/cf.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

  - task: apply-product-changes-nsx-t
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/apply-product-changes.yml
    attempts: 10
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/vmware-nsx-t.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

  - task: apply-product-changes
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/apply-product-changes.yml
    attempts: 10
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

- name: pas-errands
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      passed: [ pas ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: configuration

  - task: run-smoke_tests
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: smoke_tests
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-push-usage-service
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: push-usage-service
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-push-apps-manager
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: push-apps-manager
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-deploy-notifications
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-notifications
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-deploy-notifications-ui
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-notifications-ui
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-deploy-autoscaler
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-autoscaler
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-nfsbrokerpush
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: nfsbrokerpush
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-test-autoscaling
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-notifications-ui
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first




- name: unlock-tile
  serial: true
  plan:
  - get: configuration
    trigger: true
    passed:
    - "pas-errands"
  - get: lock
  - put: lock
    params:
      release: lock
