resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    #product_version: 5\.1\.1*

- name: configuration
  type: git
  source:
    branch: azeem
    uri: git@github.com:tonyelmore/telmore-platform-automation.git
    private_key: ((plat-auto-pipes-deploy-key.private_key))
    paths:
    - "environments/((iaas))/((foundation))/pipeline.yml"
    - "environments/((iaas))/((foundation))/config"


jobs:
- name: validate-tile-configuration
  plan:
  - in_parallel:
    - get: configuration
      #trigger: true
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image-5.1.2.tar.gz"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["platform-automation-tasks-5.1.2.zip"]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: &credhub_interpolate_params
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      PREFIX: '/concourse/((team))'
      CREDHUB_CA_CERT: |
          -----BEGIN CERTIFICATE-----
          MIIDUDCCAjigAwIBAgIUXOUM1M+/JA1ksNvS8iDambOd61gwDQYJKoZIhvcNAQEL
          BQAwHzELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bpdm90YWwwHhcNMjQwMTAyMDQz
          MjQ4WhcNMjgwMTAyMDQzMjQ4WjAfMQswCQYDVQQGEwJVUzEQMA4GA1UECgwHUGl2
          b3RhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANPNNrHMPrIjfa4m
          w0vmw5A4gRLT/ByAggCG1/i1VLCeyB8rJZVR4a4eI8SL4fycZVxTkR9jIHw8X8Tz
          p6gMfsDhryNOuef3VZmn8evJ6Jf+C6jYfXFYUQ/KV3Cn8DH+aEDkDl5gWOp/5K72
          KcVAyRKUs0jZgWqx4mMqeeuAYUWvwMT3FuJEsHn2kLP/J4J+R3hzw4+rFTM5VNao
          ClRuyOUCirqC5TKewpGrg2FXrc5AiCb9zqYfbhw/pRTu20osIvDgCsBiiD7xfnZH
          GK8/NNRe2A0vNBXb213JvOwonb+Jq8WeI32VC0bUfvXH9k75EBGVcIfSUWK1YEQ3
          M8EA2OECAwEAAaOBgzCBgDAdBgNVHQ4EFgQUm55v8asqZdejFZXzgj6gsE44rEUw
          HwYDVR0jBBgwFoAUm55v8asqZdejFZXzgj6gsE44rEUwHQYDVR0lBBYwFAYIKwYB
          BQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEG
          MA0GCSqGSIb3DQEBCwUAA4IBAQBZi4ZoPcaOLmelVKaVa2Ekxf7h81Sn1E6FzosX
          Gvabcr2B3JxSbEUavEs+UurdT91lIakMI474Nyx4Y+Vcw/ilkw3BRjNsCJ2zr6Kh
          /GAEoB6/xngPgltySUieBdQvwgA3LEVl7bGAn/y50k1FJvdYbrlN9WhRJx6flkD6
          qk2mtrE8w/aFUJafSGJpr2tGArjRqgyTmarxh6VlEV6qwBBZb/nLBSHQ9TsdKVCM
          XgT09lq285+Tt80Xd6kGBgcljdAznE1NCNVtE16zt+ENoOhAMCSdMhWtn99nSmL8
          7PmNJo5p0/dFA4HxM++QznQEmAqbgIEGFLwwLQRmW6hyBQYP
          -----END CERTIFICATE-----
      INTERPOLATION_PATHS: "environments/((iaas))/((foundation))/config/secrets"
    input_mapping:
      files: configuration

- name: pas
  serial: true
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: [ validate-tile-configuration ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image-5.1.2.tar.gz"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["platform-automation-tasks-5.1.2.zip"]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: configuration

  - task: download-stage-tile-stemcell
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/download-stage-tile-stemcell.yml
    input_mapping:
      config: configuration
      download-config: configuration
      env: interpolated-files
      secrets: interpolated-files
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf.yml
      DOWNLOAD_STEMCELL_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf-stemcell.yml
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      VARS_FILES: secrets/environments/((iaas))/((foundation))/config/secrets/pivnet.yml

  - task: configure
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: interpolated-files
      vars: configuration
      secrets: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      VARS_FILES: |
        vars/environments/((iaas))/((foundation))/config/defaults/cf.yml
        vars/environments/((iaas))/common/cf.yml
        vars/environments/((iaas))/((foundation))/config/vars/cf.yml
        secrets/environments/((iaas))/((foundation))/config/secrets/cf.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

  - task: apply-product-changes
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/apply-product-changes.yml
    attempts: 10
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml

- name: pas-errands
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
      passed: [ pas ]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["vsphere-platform-automation-image-5.1.2.tar.gz"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["platform-automation-tasks-5.1.2.zip"]

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *credhub_interpolate_params
    input_mapping:
      files: configuration

  - task: run-smoke_tests
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: smoke_tests
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-push-usage-service
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: push-usage-service
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-push-apps-manager
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: push-apps-manager
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-deploy-notifications
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-notifications
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-deploy-notifications-ui
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-notifications-ui
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-deploy-autoscaler
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-autoscaler
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-nfsbrokerpush
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: nfsbrokerpush
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first

  - task: run-test-autoscaling
    attempts: 5
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/run-errand.yml
    input_mapping:
      config: configuration
      env: interpolated-files
    params:
      CONFIG_FILE: environments/((iaas))/((foundation))/config/templates/cf.yml
      ERRAND_NAME: deploy-notifications-ui
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
      INSTANCE: clock_global/first
