resources:
- name: configuration
  type: git
  source:
    branch: master
    password: ((github_token))
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    username: ((github_username))
    paths:
    - "environments/((iaas))/((foundation))/test-config"

- name: lock
  type: pool
  source:
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    branch: master
    username: ((github_username))
    password: ((github_token))
    pool: locks/test
    retry_delay: 1m

jobs:
- name: force-unlock
  serial: true
  plan:
  - get: lock
  - put: lock
    params:
      release: lock

- name: lock-product
  serial: true
  plan:
  - in_parallel:
    - put: lock
      params: {acquire: true}
    - get: configuration
      trigger: true

- name: unlock-product
  serial: true
  plan:
  - get: configuration
    trigger: true
    passed:
    - "lock-product"
  - get: lock
  - put: lock
    params:
      release: lock
