db-and-errand-runner_enable_logs: true
db-and-errand-runner_postgres_ciphers: HIGH:+3DES:!aNULL
db-and-errand-runner_use_socks_proxy: false
log-store-vms_log_store_enable_event_alerting: false
log-store-vms_log_store_partition_count: 64
log-store-vms_log_store_prune_interval: 2m
log-store-vms_log_store_prune_threshold: 80
log-store-vms_log_store_replication_factor: 2
log-store-vms_log_store_retention_period: 42
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
delete-space_pre_delete_state: default
migrate-route_post_deploy_state: default
push-app-metrics_post_deploy_state: default
smoke-test_post_deploy_state: default
resource-var-db-and-errand-runner_instance_type: automatic
resource-var-db-and-errand-runner_max_in_flight: default
resource-var-db-and-errand-runner_persistent_disk_size: automatic
resource-var-log-store-vms_instance_type: automatic
resource-var-log-store-vms_instances: automatic
resource-var-log-store-vms_max_in_flight: default
resource-var-log-store-vms_persistent_disk_size: automatic
