cert-expiration-exporter_skip_ssl_validation: false
pas-sli-exporter_cf_cli_version: "7"
skip_custom_app_metrics: false
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
bosh-cleanup-wait_pre_delete_state: default
delete-cf-sli-user_pre_delete_state: default
smoke-test_post_deploy_state: default
resource-var-bosh-deployments-exporter_instance_type: automatic
resource-var-bosh-deployments-exporter_instances: automatic
resource-var-bosh-deployments-exporter_max_in_flight: default
resource-var-bosh-deployments-exporter_persistent_disk_size: automatic
resource-var-bosh-health-exporter_instance_type: automatic
resource-var-bosh-health-exporter_instances: automatic
resource-var-bosh-health-exporter_max_in_flight: default
resource-var-bosh-health-exporter_persistent_disk_size: automatic
resource-var-cert-expiration-exporter_instance_type: automatic
resource-var-cert-expiration-exporter_instances: automatic
resource-var-cert-expiration-exporter_max_in_flight: default
resource-var-cert-expiration-exporter_persistent_disk_size: automatic
resource-var-pas-exporter-counter_instance_type: automatic
resource-var-pas-exporter-counter_instances: automatic
resource-var-pas-exporter-counter_max_in_flight: default
resource-var-pas-exporter-counter_persistent_disk_size: automatic
resource-var-pas-exporter-gauge_instance_type: automatic
resource-var-pas-exporter-gauge_instances: automatic
resource-var-pas-exporter-gauge_max_in_flight: default
resource-var-pas-exporter-gauge_persistent_disk_size: automatic
resource-var-pas-sli-exporter_instance_type: automatic
resource-var-pas-sli-exporter_instances: automatic
resource-var-pas-sli-exporter_max_in_flight: default
resource-var-pas-sli-exporter_persistent_disk_size: automatic
resource-var-svm-forwarder_instance_type: automatic
resource-var-svm-forwarder_instances: automatic
resource-var-svm-forwarder_max_in_flight: default
resource-var-svm-forwarder_persistent_disk_size: automatic
