deploy-scheduler_enable_calls: true
deploy-scheduler_quartz_acquire_triggers_within_lock: true
create-uaa-client_post_deploy_state: default
deploy-scheduler_post_deploy_state: default
destroy-scheduler_pre_delete_state: default
publicize-scheduler_post_deploy_state: default
register-broker_post_deploy_state: default
test-scheduler_post_deploy_state: default
resource-var-create-uaa-client_instance_type: automatic
resource-var-create-uaa-client_max_in_flight: default
resource-var-deploy-scheduler_instance_type: automatic
resource-var-deploy-scheduler_max_in_flight: default
resource-var-destroy-scheduler_instance_type: automatic
resource-var-destroy-scheduler_max_in_flight: default
resource-var-publicize-scheduler_instance_type: automatic
resource-var-publicize-scheduler_max_in_flight: default
resource-var-register-broker_instance_type: automatic
resource-var-register-broker_max_in_flight: default
resource-var-test-scheduler_instance_type: automatic
resource-var-test-scheduler_max_in_flight: default
