cc_exporter_enabled: true
global_wavefront_service_broker_access: true
quota_collector_enabled: false
rabbitmq_per_object_metrics_enabled: false
service_bindings_enabled: false
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
tas-exporters_latency_forwarder_buffer_size: 10000
tas-exporters_latency_forwarder_worker_count: 10
telegraf_agent_flush_interval: 15
telegraf_agent_interval: 15
telegraf_agent_metric_buffer_limit: 30000
wavefront_legacy_service_bindings: false
bosh-cleanup-wait_pre_delete_state: default
delete-cf-sli-user_pre_delete_state: default
delete-v3-cf-nozzle_post_deploy_state: default
register-cf-service-broker_post_deploy_state: default
resource-var-pas-exporter-container_instance_type: automatic
resource-var-pas-exporter-container_instances: automatic
resource-var-pas-exporter-container_max_in_flight: default
resource-var-pas-exporter-container_persistent_disk_size: automatic
resource-var-pas-exporter-counter_instance_type: automatic
resource-var-pas-exporter-counter_instances: automatic
resource-var-pas-exporter-counter_max_in_flight: default
resource-var-pas-exporter-counter_persistent_disk_size: automatic
resource-var-pas-exporter-gauge_instance_type: automatic
resource-var-pas-exporter-gauge_instances: automatic
resource-var-pas-exporter-gauge_max_in_flight: default
resource-var-pas-exporter-gauge_persistent_disk_size: automatic
resource-var-pas-exporter-timer_instance_type: automatic
resource-var-pas-exporter-timer_instances: automatic
resource-var-pas-exporter-timer_max_in_flight: default
resource-var-pas-exporter-timer_persistent_disk_size: automatic
resource-var-tas-exporters_instance_type: automatic
resource-var-tas-exporters_instances: automatic
resource-var-tas-exporters_max_in_flight: default
resource-var-tas-exporters_persistent_disk_size: automatic
resource-var-telegraf_agent_instance_type: automatic
resource-var-telegraf_agent_instances: automatic
resource-var-telegraf_agent_max_in_flight: default
resource-var-telegraf_agent_persistent_disk_size: automatic
resource-var-telegraf_standalone_instance_type: automatic
resource-var-telegraf_standalone_instances: automatic
resource-var-telegraf_standalone_max_in_flight: default
resource-var-telegraf_standalone_persistent_disk_size: automatic
resource-var-wavefront_proxy_instance_type: automatic
resource-var-wavefront_proxy_instances: automatic
resource-var-wavefront_proxy_max_in_flight: default
resource-var-wavefront_proxy_persistent_disk_size: automatic
