cloud_controller_apps_domain: apps.sbx.covertcoding.com
cloud_controller_system_domain: sys.sbx.covertcoding.com
singleton_availability_zone: us-west1-a
az2_name: us-west1-b
az3_name: us-west1-c

# resource-var-router_elb_names: ["sbx-web-lb"]
# resource-var-router_additional_vm_extensions: ["web-lb-security-group"]
# resource-var-diego_brain_elb_names: ["sbx-diego-ssh-lb"]
# resource-var-diego_brain_additional_vm_extensions: ["ssh-lb-security-group"]
# resource-var-tcp_router_elb_names: ["sbx-tcp-lb"]
# resource-var-tcp_router_additional_vm_extensions: ["tcp-lb-security-group"]