cloud_controller_apps_domain: apps.sbx.my3votes.com
cloud_controller_system_domain: sys.sbx.my3votes.com
singleton_availability_zone: zone-1
az2_name: zone-2
az3_name: zone-3

resource-var-router_elb_names: ["sbx-web-lb"]
resource-var-router_additional_vm_extensions: ["web-lb-security-group"]
resource-var-diego_brain_elb_names: ["sbx-diego-ssh-lb"]
resource-var-diego_brain_additional_vm_extensions: ["ssh-lb-security-group"]
resource-var-tcp_router_elb_names: ["sbx-tcp-lb"]
resource-var-tcp_router_additional_vm_extensions: ["tcp-lb-security-group"]