cloud_controller_apps_domain: apps.h2o-2-23016.h2o.vmware.com
cloud_controller_system_domain: sys.h2o-2-23016.h2o.vmware.com
singleton_availability_zone: az1
enable_smb_volume_driver: false

# cloud_controller_fs4_only_fs3_and_fs4_option_cloud_controller_default_stack: cflinuxfs3
enable_log_cache_syslog_ingestion: true

# resource-var-diego_brain_instances: 1
resource-var-router_instances: 2
resource-var-router_additional_vm_extensions: ["tas_gorouter_vm_extension"]
# resource-var-diego_cell_instances: 3
resource-var-diego_brain_additional_vm_extensions: ["tas_ssh_vm_extension"]
resource-var-tcp_router_additional_vm_extensions: ["pas_tcp_vm_extension"]