---
service_network_name: services
plan1_selector_single_node_az_multi_select: ["az1"]
plan2_selector_single_node_az_multi_select: ["az1"]
plan3_selector_single_node_az_multi_select: ["az1"]

global_recipient_email: test@me.com
deprecated_bindings_string: X
