jobs:
- name: hello-world-job
  plan:
  - task: print-hello-world
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["hello world"]
